# Generated by Django 4.1.4 on 2022-12-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_managers_alter_post_teg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teg',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_name',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='teg',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='teg_name',
            new_name='tag_name',
        ),
    ]
